version: '3.10'
services:
  calliope:
    # platform: linux/arm64/v8
    build:
      context: .
    command: bash
    container_name: calliope_service
    environment:
      - DOCKER_REGISTRY_URL
    networks:
      default:
        aliases:
          - calliope
    ports:
      - 8000:8000
    tty: true
    volumes:
      - .:/app
      - /app/.venv
