services:
  postgres:
    hostname: postgres
    image: postgres:12.4
    environment:
      - POSTGRES_DB=calliope
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "4433:4433"
    volumes:
      - ./data:/var/lib/postgresql/data
  calliope:
    # platform: linux/arm64/v8
    build:
      context: .
    # command: bash
    command: uv run uvicorn calliope.app:app --reload --host 0.0.0.0 --port 8008
    container_name: calliope
    depends_on:
      - postgres
    environment:
      - PORT=8008
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=calliope
      - CLOUDSDK_CONFIG=/gcp/config
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - GOOGLE_CLOUD_PROJECT=ardent-course-370411
      - CLOUD_ENV=local
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PINECONE_API_KEY=$PINECONE_API_KEY
      - PINECONE_ENVIRONMENT=us-west1-gcp-free
      - SEMANTIC_SEARCH_INDEX=story-semantic-search
      - FIREBASE_DATABASE_ID=calliope-development
      # Use the same credentials file for Firebase - Firebase Admin SDK will
      # gracefully fall back to application default credentials if needed
      - FIREBASE_CREDENTIALS_PATH=/gcp/config/application_default_credentials.json
    ports:
      - 8008:8008
    tty: true
    volumes:
      - .:/app
      - /app/.venv  # Preserve container's virtual environment
      - $HOME/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
      # Mount specific directories that need to be persistent
      - ./config:/app/config
      - ./input:/app/input
      - ./media:/app/media
      - ./state:/app/state
