version: '3.10'
services:
  postgres:
    hostname: postgres
    image: postgres:12.4
    environment:
      - POSTGRES_DB=calliope
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "4433:4433"
    volumes:
      - ./data:/var/lib/postgresql/data
  calliope:
    # platform: linux/arm64/v8
    build:
      context: .
    # command: bash
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8008
    container_name: calliope
    depends_on:
      - postgres
    environment:
      - PORT=8008
      - POSTGRESQL_HOSTNAME=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=calliope
      - CLOUDSDK_CONFIG=/gcp/config
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/config/application_default_credentials.json
      - CLOUD_ENV=local
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PINECONE_API_KEY=$PINECONE_API_KEY
      - PINECONE_ENVIRONMENT=us-west1-gcp-free
      - SEMANTIC_SEARCH_INDEX=story-semantic-search
    ports:
      - 8008:8008
    tty: true
    volumes:
      - .:/app
      - /app/.venv
      - $HOME/.config/gcloud:/gcp/config:ro
      - /gcp/config/logs
